spring:
  application:
    name: zuul-server

eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8070/eureka

      fetchRegistry: true
      instance:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


server:
  port: 8080

zuul:
  routes:
    echo:
      path: /**
      serviceId: erp-master
      stripPrefix: true

