spring:
  application:
    name: fleet-manager

eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8070/eureka
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream